// Simulando um banco de dados de direitos do cidadão

export const direitos = [
  {
    id: '1',
    titulo: 'Direito à Saúde Atualizado',
    categoria: 'Saúde',
    conteudo: 'Todo cidadão tem direito ao acesso universal e igualitário às ações e serviços de saúde.'
  },
  {
    id: '2',
    titulo: 'Direito à Educação',
    categoria: 'Educação',
    conteudo: 'A educação é um direito de todos e dever do Estado e da família.'
  },
  {
    id: '3',
    titulo: 'Direito ao Voto',
    categoria: 'Cidadania',
    conteudo: 'O voto é direto e secreto e todos os cidadãos maiores de 16 anos podem votar.'
  },
  {
    id: '4',
    titulo: 'Direito ao Transporte',
    categoria: 'Infraestrutura',
    conteudo: 'É dever do Estado garantir o transporte público acessível e de qualidade.'
  },
  {
    id: '5',
    titulo: 'Direito à Segurança',
    categoria: 'Segurança',
    conteudo: 'Todos têm direito à proteção e segurança pessoal e pública.'
  }
];
